# Generated by Django 4.2.7 on 2025-03-15 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('file', models.FileField(blank=True, null=True, upload_to='exams/', verbose_name='file')),
                ('format', models.CharField(choices=[('text', 'Text'), ('markdown', 'Markdown'), ('latex', 'LaTeX'), ('pdf', 'PDF')], default='text', max_length=10, verbose_name='format')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='deadline')),
            ],
            options={
                'verbose_name': 'exam',
                'verbose_name_plural': 'exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='question text')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='points')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('model_answer', models.TextField(blank=True, verbose_name='model answer')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'ordering': ['order'],
            },
        ),
    ]
